---
title: ""
author: ""
date: ""
output: 
  html_document: 
    highlight: pygments
    theme: united
---
## Biology 264 - Community Ecology
### Spring 2016
### Nicholas J. Gotelli

Welcome to the homepage for Biology 264. Follow the links below each dated post to pages for course material. The most recent postings are always at the top.

****

#### 21 April 2016

Key to Exam 3:

[Key to Exam#3 (html)](HomeworkAssignments/Exam3_Solutions.html)

[Key to Exam#3 (pdf)](HomeworkAssignments/Exam3_Solutions.pdf)

#### 10 April 2016
[Annotating Data Sets (pdf)](LecturePresentations/Annotating_Data_Sets.pdf)

#### 6 April 2016

For this week's homework solution, I am posting Brian O'Malley's code. Note how he has created a 4-panel display with the same color-coded isoclines in each graph.

[Solutions to Homework #4 (html)](HomeworkAssignments/Homework_4_Solutions.html)



R scripts for regression simulator, contingency analysis (updated), and logistic regression: 

[RegressionSimulator.R](LecturePresentations/RegressionSimulator.R)

[ContingencyAnalysis.R](LecturePresentations/ContingencyAnalysis.R)

[LogisticRegression.R](LecturePresentations/LogisticRegression.R)

****
#### 31 March 2016

R scripts for ANOVA simulator and probability distributions:

[ANOVASimulator.R](LecturePresentations/ANOVASimulator.R)

[ContinuousProbabilityDistributions.R](LecturePresentations/ContinuousProbabilityDistributions.R)

[DiscreteProbabilityDistributions.R](LecturePresentations/DiscreteProbabilityDistributions.R)


****

#### 17 March 2016

[Epimodel R Package](http://www.epimodel.org/) from Brandon Ogbunu's guest lecture.

****
#### 15 March 2016

R scripts for two-species dynamics models:

[TwoSpeciesGrowthDymamics.R](LecturePresentations/TwoSpeciesGrowthDynamics.R)

[TwoSpeciesStateSpace.R](LecturePresentations/TwoSpeciesStateSpace.R)


New homework assignment:

[Homework #4: due 29 Mar 2016](HomeworkAssignments/Homework_4.html)

Key to Exam 2:

[Key to Exam#2 (html)](HomeworkAssignments/Exam2_Solutions.html)

[Key to Exam#2 (pdf)](HomeworkAssignments/Exam2_Solutions.pdf)



****
#### 29 February 2016
Ecology equations from class

Title | Equation | X variable | Y Variable | Parameters
--|--|--|--|--
Species Area Power Function | $S=cA^z$ | $A$ | $S$ | $c,z$
Exponential Growth | $\frac{dN}{dt}=rN$ | $t$ | $N$ | $N_0,r$
Logistic Growth | $\frac{dN}{dt}=rN\left(1-\frac{N}{K}\right)$ | $t$ | $N$ | $N_0,r,K$
Ricker Growth | $N_{t+1}=N_te^\left(1-\frac{N_t}{K}\right)$ | $t$ | $N$ | $N_0,r,K$
von Bertalanffy Growth | $L_{t+1}=r(L_{max}-L_t)$ | $t$ | $L$ | $r,L_{max}$
Michaelis-Menten (Holling Type II) | $F=\frac{aV}{1+ahV}$ | $V$ | $F$ | $a,h$


[Solutions to Homework #3 (html)](HomeworkAssignments/Homework_3_Solutions.html)

[Solutions to Homework #3 (pdf)](HomeworkAssignments/Homework_3_Solutions.pdf)

#### 23 February 2016
Here are the R script files I have generated for lecture presentations this semester:

[GrowthDymamics.R](LecturePresentations/GrowthDynamics.R)

[PlottingFunctions.R](LecturePresentations/PlottingFunctions.R)

[R_ControlFunctions.R](LecturePresentations/R_ControlFunctions.R)

[R_DataStructures.R](LecturePresentations/R_DataStructures.R)

[R_ForLoops.R](LecturePresentations/R_ForLoops.R)

[R_Functions.R](LecturePresentations/R_Functions.R)


****
#### 16 February 2016
[Homework #3: due 23 Feb 2016](HomeworkAssignments/Homework_3.html)

****
#### 14 February 2016
[Key to Exam#1 (html)](HomeworkAssignments/Exam1_Solutions.html)

[Key to Exam#1 (pdf)](HomeworkAssignments/Exam1_Solutions.pdf)


#### 07 February 2016
[Solutions to Homework#2 (html)](HomeworkAssignments/Homework_2_Solutions.html)

[Solutions to Homework#2 (pdf)](HomeworkAssignments/Homework_2_Solutions.pdf)

****
#### 28 January 2016
["Fun Facts" about the students in Bio 264](CourseMaterials/FunFacts.html)

[Homework #2: due 04 Feb 2016](HomeworkAssignments/Homework_2.html)

I know that some of you are still wrestling with the LaTeX installation on Windows machines. Fortunately, one of your fellow students, Justin Sell, happens to work for IT here at UVM (see the [Fun Facts](CourseMaterials/FunFacts.html) page)! Justin writes:

 > I spent about 2 hours playing around and trying to figure out how this little guy works- my findings are:
 
- I am running a PC that is 64-bit
- I tried the basic install for a 32-bit computer and it doesn't look like that worked for me
- I opened R-studio to check and see if it was using the 32-bit or 64-bit version of R and it appeared to be using the 64-bit version
- I went online and did some research and found the proper installer for 64-bit PC's:

    1.  http://miktex.org/download
    2.  Go to "Other Downloads"
    3.  Select the MiKTeX 2.9.5840 64-bit Net Installer (11.13MB) and save it to the desktop
    4.  Run the installer selecting the download MiKTeX and choose the complete not the basic
    5.  Find a mirror of your choice
    6.  Allow the installer to complete.  Once it is completed, you should notice a folder with the downloaded files on your desktop
    7.  Run the same installer AGAIN this time instead of choosing the download option, choose the install from a local directory and browse to the new folder that the installer made on the desktop
    8.  Once complete, the program should be installed and you can test the PDF exporter

Thank you, Justin! If you are still stuck, don't sweat it because you won't need to compile to `.pdf` again until  you give your final presentation, which we can always do for you on another machine.

****

#### 22 January 2016

[Homework #1: due 28 Jan 2016](HomeworkAssignments/Homework_1.html)

You all did a good job on your first day working with RStudio and Markdown. If you ar still having trouble with LaTeX, make sure you have the latest versions of RStudio and R installed. If that doesn't work, try uninstalling everything and reinstalling fresh (time-consuming, but you can't hurt anything). Please see me or contact Devin (dlmuelle@uvm.edu) for additional help. Don't sweat it if you simply cannot get LaTeX installed and working. The only thing you really need it for is your final presentation, and we can knit your file separately on a different machine to set that up.

I modified the homework assignment this week so that you will just turn in your `.html` files, which should have your imbedded images. For more typical assignments, I will collect your `.Rmd` or `.R` files and run them myself.

For turning in homeworks, I think the simplest solution is for you to get your own flash drive (they are available in the bookstore), copy your homework onto it, and then I will copy it onto my machine (we can certainly do some of that before class starts on Thursday). Although this is a little more time consuming for each of  you, it means I can leave class with all of your homework in a single folder on my desktop, which is a huge time savings for me. *Thank you!*

Last time, Justin Sell asked me whether we could use the line equation in Markdown to create a centered html headline like this:

```
$$Hacking A Centered Headline$$
```

But if you try that in your Markdown file, you will get this:

$$Hacking A Centered Headline$$

The problem is that LaTex thinks you are writing out math variables which should be displayed as if they are being multiplied together, with the spaces stripped out. Try this instead:

```
$$\text{Hacking A Centered Headline}$$
```
now you will see:

$$\text{Hacking A Centered Headline}$$

To find this solution, I searched on the web for "plain text in LaTeX equations" and ended up at the LaTeX wiki, which had the solution.

This is exactly how you will answer your own questions about R and LaTeX when you are trying to do new things.




****

#### 11 January 2016

[Course Description](CourseMaterials/CourseDescription.pdf)

[Lecture Schedule](CourseMaterials/LectureSchedule.pdf)

[Personal Pledge](CourseMaterials/PersonalPledge.pdf)

****

#### 22 December 2015

[Instructions For Loading Software](Dec22/SoftwareInstructions.html)

[CheatSheets And Resources For R Programming](Dec22/CheatSheets.html)
